# 东方财富 - session
eastmoney:
  validatekey: 2fc312a2-2730-59fa-a71a-6daf309390f0
  cookie: st_si=7845973208075; st_asi=delete; b-user-id=5gfv23hw-d31c-3f53-99ce-e660u3jhgwe102de; st_pvi=69309129852821043795; st_sp=2025-05-01%2001%3A25%3A07; st_inirUrl=https%3A%2F%2Fwww.eastmoney.com%2F; st_sn=01; st_psi=202505011000005345-11234501-282323; Yybdm=9527; Uid=XV%8dfe213safYqI7hg33522dDJSew%3D%3D; mobileimei=bda537db-b638-5d73-735ac913915f; Uuid=db7eb9edsd7603210ddfksd03093362097ad2



# 通达信-根目录
tdx-path: "C:/soft/new_tdx"



# 数据源配置 - 使用 ShardingSphere 5.5.x 新方式
spring:
  datasource:
    # Druid 监控配置
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name: user
        principal-cookie-name: user
        profile-enable: true



logging:
  level:
    # 全局日志级别
    root: INFO
    # tdx-quant
    com.bebopze.tdx.quant: INFO
    # 行情数据
    com.bebopze.tdx.quant.parser: INFO
    # 批量回测
    com.bebopze.tdx.quant.strategy: ERROR